name: Build and test

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: User_123
        ports:
        - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
    steps:
    - name: Verify MySQL connection from host
      run: |
        sudo apt-get install -y mysql-client
        mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -pUser_123 -e "SHOW DATABASES"

    - name: checkout source
      uses: actions/checkout@v2
    
    - name: setup golang
      uses: actions/setup-go@v2

    - name: start redis
      uses: supercharge/redis-github-action@1.2.0
    
    - name: setup jdk
      uses: actions/setup-java@v1
      with:
        java-version: '11' # The JDK version to make available on the path.
        java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
        architecture: x64 # (x64 or x86) - defaults to x64
    
    - name: setup zookeeper
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://archive.apache.org/dist/zookeeper/zookeeper-3.6.3/apache-zookeeper-3.6.3-bin.tar.gz
        tar -xzf apache-zookeeper-3.6.3-bin.tar.gz
        cd apache-zookeeper-3.6.3-bin/conf && cp zoo_sample.cfg zoo.cfg && cd ../bin && sudo ./zkServer.sh start
        sleep 5
        sudo ps aux

    - name: build and test
      run: cd cypress && go test
      env:
        MYSQL_PORT: ${{ job.services.mysql.ports['3306'] }}